### ISSUE TITLE
Projet

### ISSUE THREAD

**Issue by idris-maps** [leyGir/VisualDon#3]
~~Quel jeux de données vas-tu utiliser? C'est quoi les mensonges que tu as en tête?~~

Pardon, j'avais pas encore vu le repo de Soraya. J'ajoute les commentaires à ce repo là si j'en ai.

Est-ce que tu peux ajouter un lien vers https://github.com/Soraya97/VisualDon/blob/master/projet/readme.md à ton fichier `/projets/readme.md`?

**Comment by leyGir** [comment]
Je fais avec Soraya Meytre. Il y a plus d'explications dans son fichier :https://github.com/Soraya97/VisualDon/tree/master/projet

**Comment by leyGir** [comment]
oui je vais le faire !

**Comment by idris-maps** [comment]
Merci. Je ferme cette "issue"
